"""Initial migration.

Revision ID: 8e1000bc169b
Revises: 
Create Date: 2024-07-24 18:50:15.159471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1000bc169b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('curs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curs',
    sa.Column('exchange_name', sa.TEXT(), nullable=True),
    sa.Column('currency_pair', sa.TEXT(), nullable=True),
    sa.Column('owner_curs', sa.INTEGER(), nullable=True)
    )
    op.drop_table('profile')
    # ### end Alembic commands ###
